---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a K8S namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/fabius-lihanda/Devops/terraform/eks_cluster/kubeconfig_myapp_eks_cluster.yaml

    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: /home/fabius-lihanda/Devops/Ansible/nginx_deployment.yaml
        state: present
        kubeconfig: /home/fabius-lihanda/Devops/terraform/eks_cluster/kubeconfig_myapp_eks_cluster.yaml
        namespace: my-app


