---
- name: Wait for host to be reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 5 # Wait for 5 seconds before starting to check
        timeout: 120 # Wait for 2 minutes for the host to be reachable

- name: Install Docker and acl package
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start Docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Install acl package
      yum:
        name: acl
        state: present

- name: Create new linux user
  hosts: all
  become: yes
  tasks:
    - name: Create new linux user
      user:
        name: fabi
        groups: adm, docker

- name: Install Docker Compose
  hosts: all
  become: yes
  become_user: fabi
  tasks:
    - name: Create Docker Compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote host
      shell: uname -m
      register: architecture
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ architecture.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x # Make the file executable

- name: Start docker containers
  hosts: all
  become: yes
  become_user: fabi
  vars_files:
    - project-vars

  # This won't work because the docker login task requires user input for the username and password and we are not in interactive mode (Running in terminal). You can either provide these values in a secure way (e.g., using Ansible Vault) or use a different method to authenticate with Docker Hub.
  # vars_prompt:
  #   - name: docker_username
  #     prompt: "Enter your Docker Hub username"
  #     private: no
  #   - name: docker_password
  #     prompt: "Enter your Docker Hub password"
  #     private: yes
  tasks:
    - name: Copy docker-compose.yml to remote host
      copy:
        src: /home/fabius-lihanda/Devops/Devops_Nana-Techworld_Bootcamp/developing-with-docker/docker-compose.yaml
        dest: /home/fabi/docker-compose.yml
    - name: Docker login
      shell: echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      no_log: true
    - name: Start Docker containers
      community.docker.docker_compose_v2:
        project_src: /home/fabi
        
